// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF3xZot3cx6HUGSUZFKQoSRKARLRVtwmk',
    appId: '1:72023272698:web:d43bb407edefbdbf746d43',
    messagingSenderId: '72023272698',
    projectId: 'fir-auth-83982',
    authDomain: 'fir-auth-83982.firebaseapp.com',
    storageBucket: 'fir-auth-83982.firebasestorage.app',
    measurementId: 'G-3QSZFSHRK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDtHxHy7ZG5RV_ykVRftQh6fPX8ihu1sY',
    appId: '1:72023272698:android:3c65c41d7e7da304746d43',
    messagingSenderId: '72023272698',
    projectId: 'fir-auth-83982',
    storageBucket: 'fir-auth-83982.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1F4OrzXLWoV1CGWGZDnvg2HkdWppsbQo',
    appId: '1:72023272698:ios:118ca0b1ac7ae085746d43',
    messagingSenderId: '72023272698',
    projectId: 'fir-auth-83982',
    storageBucket: 'fir-auth-83982.firebasestorage.app',
    iosBundleId: 'com.example.medimate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1F4OrzXLWoV1CGWGZDnvg2HkdWppsbQo',
    appId: '1:72023272698:ios:118ca0b1ac7ae085746d43',
    messagingSenderId: '72023272698',
    projectId: 'fir-auth-83982',
    storageBucket: 'fir-auth-83982.firebasestorage.app',
    iosBundleId: 'com.example.medimate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF3xZot3cx6HUGSUZFKQoSRKARLRVtwmk',
    appId: '1:72023272698:web:183f2d436f47ccee746d43',
    messagingSenderId: '72023272698',
    projectId: 'fir-auth-83982',
    authDomain: 'fir-auth-83982.firebaseapp.com',
    storageBucket: 'fir-auth-83982.firebasestorage.app',
    measurementId: 'G-HC9H2WCGY4',
  );
}
